name: Ubuntu - Test

on: [pull_request]

jobs:
  build:
    name: Test on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      #- name: Set up Zalenium
      #  run: docker-compose -f docker-compose_zalenium.yml up --force-recreate -d
      - name: Set up Native Selenium Grid
        run: docker-compose -f docker-compose_native.yml up --scale chrome=4 --remove-orphans -d
      - name: Set up JDK 14
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 14
      - name: Check running containers
        run: docker ps
      - name: Run all tests
        run: mvn test -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="Linux-64" -DmaximumPerformanceMode="true" -DtargetBrowserName="GoogleChrome" -Dtest="!%regex[.*checksum.*], !%regex[.*cucumber.*], !%regex[.*sikulix.*], !%regex[.*imageComparison.*], !%regex[.*FileActions.*], !%regex[.*TerminalActions.*], !%regex[.*localShell.*], !%regex[.*fullPageScreenshotWithHeader.*], !%regex[.*dbConnection.*], !%regex[.*Appium.*]" -Dmaven.artifact.threads=30
